# HSE project information
site_name: HSE Project
site_url: https://hse-project.github.io/2.x
site_description: >-
  Fast embeddable key-value store designed for SSDs and persistent memory


# HSE repo information (source code not docs)
# Setting these results in hse repo link and stats in doc header
repo_url: https://github.com/hse-project/hse
repo_name: hse-project/hse
edit_uri: ""


# Documentation copyright notice
copyright: Copyright &copy; 2020 - 2022 Micron Technology, Inc.


# HSE colors set in docs/stylesheets/extra.css
extra_css:
  - stylesheets/extra.css


# Theme configuration
theme:
  name: material
  # custom_dir extends the material theme to add an announcement bar
  # indicating that HSE 2.x is no longer actively maintained
  custom_dir: overrides
  language: en
  favicon: img/favicon.png
  logo: img/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections


# Theme customization
extra:
  version:
    # mike is a natively supported external utility for MkDocs versioning
    provider: mike


# Useful markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Plugins providing additional functionality for this theme
plugins:
  - search


# Page navigation
nav:
  - Home: index.md
  - Getting Started:
    - About: gs/about.md
    - KVDB Storage: gs/storage.md
    - Configuration Parameters: gs/params.md
    - Command Line Interface: gs/cli.md
    - System Requirements: gs/sysreqs.md
  - Developing HSE Apps:
    - Concepts: dev/concepts.md
    - Best Practices: dev/bp.md
    - Limits: dev/limits.md
  - Resources:
    - Community: res/community.md
    - Benchmarking Tips: res/benchmarking.md
  - API Reference:
    - Overview: api/c/index.md
    - Version Information: api/c/Modules/group__VERSION.md
    - Errors: api/c/Modules/group__ERRORS.md
    - Subsystem:  api/c/Modules/group__SUBSYS.md
    - Key-Value Database (KVDB): api/c/Modules/group__KVDB.md
    - Key-Value Store (KVS): api/c/Modules/group__KVS.md
    - Transactions: api/c/Modules/group__TRANSACTIONS.md
    - Cursors: api/c/Modules/group__CURSORS.md
